import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
//import { useTranslation } from 'next-i18next';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	//const { i18n } = useTranslation();

	return (
		<html lang="en">
			<body className={inter.className}>
				{/*<div>*/}
				{/*	<button onClick={() => i18n.changeLanguage('en')}>*/}
				{/*		/!* Flag icon for English *!/*/}
				{/*	</button>*/}
				{/*	<button onClick={() => i18n.changeLanguage('fr')}>*/}
				{/*		/!* Flag icon for French *!/*/}
				{/*	</button>*/}
				{/*	<a href="/path-to-your-cv.pdf" download>*/}
				{/*		Download PDF*/}
				{/*	</a>*/}
				{/*</div>*/}
				{children}
			</body>
		</html>
	);
}
